### ISSUE TITLE
404 /repo/image not found

### ISSUE THREAD

**Issue by rubenelshof** [chickenbellyfin/registry-ui#1]
First of thank you for creating this interface.

I get the following error when accessing a image.
```
⚠️ 404 — Not Found
Requested URL /repo/diony/base not found
```

After a quick test it appears that viewing a image does not work when it is placed in a separate repository.
For example:
`registry.test.com/test` will show the tag list
`registry.test.com/diony/base` will not show the tag list & 404's

**Comment by chickenbellyfin** [comment]
The url would be /repo/{repo} for tag list or /image/{repo}/{tag} for image details

**Comment by rubenelshof** [comment]
Sorry had the wrong URL's listed.
Please see below
`https://registry.test.com/repo/test` will show the tag list
`https://registry.test.com/image/test/latest` shows image details

`https://registry.test.com/repo/diony/base` will not show the tag list & 404's
`https://registry.test.com/image/diony/base/latest` 404

**Comment by chickenbellyfin** [comment]
I see, "diony/base" is the name of the repo? That would indeed a bug, it's not handling / in the repo name.

**Comment by rubenelshof** [comment]
Correct.

**Comment by chickenbellyfin** [comment]
Thanks for reporting, I pushed a new version which should handle this correctly.
